def shahzaib(name='default value'):
    print("g00d morning "+name)
shahzaib('jerry')    
shahzaib('jerry')    
shahzaib('jerry')    
shahzaib('jerry')    
shahzaib('jerry')    
shahzaib('jerry')    
shahzaib('jerry')    
shahzaib('jerry')    
shahzaib('jerry')    
shahzaib('jerry')    
shahzaib('jerry')    
shahzaib('jerry')    
shahzaib('jerry') 
shahzaib()   
